### ISSUE TITLE
error

### ISSUE THREAD

**Issue by k9team3** [jcontini/facebook-scraper#1]
try the code but itś not working for me. i tried the code with Chrome and i get the following output if i running the script. do you have sugestions to run the code and fixing the errors?

Opening browser...
Traceback (most recent call last):
  File "facebook-connections.py", line 127, in <module>
    fb_login()
  File "facebook-connections.py", line 12, in fb_login
    browser.get('https://www.facebook.com/')

  File "/root/anaconda2/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get    self.execute(Command.GET, {'url': url})

  File "/root/anaconda2/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute    self.error_handler.check_response(response)

  File "/root/anaconda2/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response   raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"5192.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.9.248304,platform=Linux 4.4.0-36-generic x86_64)

**Comment by jcontini** [comment]
Hi @k9team3, apologies for the massive delay. I had notifications off and haven't touched this in almost 2 years. The script has been updated to use python3 and Google Chrome as the browser. Could you try it again? Let me know if any more issues
