### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'db/index.json'

### ISSUE THREAD

**Issue by ghost** [jcontini/facebook-scraper#15]
I use python3.6 on ubuntu 18.04, and than chromedriver path on /home/user/bin/chromedriver. how to fix this error?? thanks

```
(facebook-scraper) dark[~/facebook-scraper] >> python extract.py 
[INFO] Script is running from shell
Opening Browser...
Please log into facebook and press enter after the page loads...
Scrolling to bottom...
db/index.html) Downloaded
Traceback (most recent call last):
  File "extract.py", line 439, in <module>
    index_friends()
  File "extract.py", line 105, in index_friends
    with open(db_index) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'db/index.json'
```

**Comment by Racater** [comment]
To fix this error, I simply created the missing file with:
`touch db/index.json`

**Comment by natejgardner** [comment]
the file `index.json` also must contain the following:

```json
{}
```

**Comment by jcontini** [comment]
Sorry about this @koboi137 @Racater @natejgardner , I've updated the script so that it creates & prepares this file going forward
