### ISSUE TITLE
Friends parsing is not working

### ISSUE THREAD

**Issue by Tvardovsky** [jcontini/facebook-scraper#23]
![CleanShot 2020-10-01 at 01 49 00](https://user-images.githubusercontent.com/7707503/94747733-587db100-0388-11eb-922f-a78bf6884f02.png)
Please check it. Thanks.

**Comment by jcontini** [comment]
Hey @Tvardovsky, I just ran the script and am not able to replicate. I tried updating the script so that it runs visibly in the browser instead of headless mode - that might make a difference. Can you pull again and see if it works for you?

If not, can I ask you to message me your `friend_list.html` to git@contini.co so I can look into it?

**Comment by surafelkifetew1** [comment]
>> Scanning downloaded profile pages...
Traceback (most recent call last):
  File "make.py", line 373, in <module>
    parse_profile_files()
  File "make.py", line 267, in parse_profile_files
    profile = parse_profile(profile_file)
  File "make.py", line 185, in parse_profile
    x = html.parse(profile_path).xpath
  File "C:\Users\.virtualenvs\facebook-friends-map-master-H0YG4eCn\lib\site-packages\lxml\html\__init__.py", line 939, in parse
    return etree.parse(filename_or_url, parser, base_url=base_url, **kw)
  File "src\lxml\etree.pyx", line 3521, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src\lxml\parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src\lxml\parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file 'file://D:\facebook\code\facebook-friends-map-master/db/profiles\100006050836.html': failed to load external entity "file://D:/4th year/4
year/2 semester/code/facebook-friends-map-master/db/profiles/100006050836.html"

OSError: Error reading file 'file://D:\facebook\code\facebook-friends-map
-master/db/profiles\100006050836.html': failed to load external entity "file://D:/facebook/code/facebook-friends-map-master/db/profiles/100006050836.html"


I am getting the above error after downloading profiles......  how can I solve this?

**Comment by petersonka5** [comment]
error
<img width="1440" alt="Képernyőfotó 2023-01-25 - 10 31 29" src="https://user-images.githubusercontent.com/123374030/214528181-2b8b5d70-4100-4ef1-b3ba-e49bcb28f247.png">

**Comment by jcontini** [comment]
Hi @petersonka5! This script uses Firefox as the browser to parse. Could you install Firefox and see if it works? 

https://www.mozilla.org/en-US/firefox/download/thanks/

Thanks!

**Comment by petersonka5** [comment]
Hi Joe!

Thank You🙂

Joe Contini ***@***.***> (időpont: 2023. jan. 26., Cs, 17:19)
ezt írta:

**Comment by petersonka5** [comment]
Download Firefox error terminal


￼

**Comment by jcontini** [comment]
Hi @petersonka5, I can't see content from your latest comment except for `Download Firefox error terminal`. If you're experiencing another error, can you try pasting the terminal content here again or taking a screenshot? Thanks!

**Comment by petersonka5** [comment]
Hi Joe!

Terminal problem run to make.py


Last login: Thu Jan 26 18:38:00 on ttys000
***@***.*** ~ % cd /Users/petermate/Downloads/facebook-friends-map-master 
***@***.*** facebook-friends-map-master % pipenv shell
Loading .env environment variables...
Loading .env environment variables...
Launching subshell in virtual environment...
 . /Users/petermate/.local/share/virtualenvs/facebook-friends-map-master-879D31Od/bin/activate
***@***.*** facebook-friends-map-master %  . /Users/petermate/.local/share/virtualenvs/facebook-friends-map-master-879D31Od/bin/activate
(facebook-friends-map-master) ***@***.*** facebook-friends-map-master % python make.py











/Users/petermate/Downloads/facebook-friends-map-master/make.py:52: DeprecationWarning: firefox_profile has been deprecated, please use an Options object
  profile = webdriver.FirefoxProfile()
/Users/petermate/Downloads/facebook-friends-map-master/make.py:59: DeprecationWarning: firefox_profile has been deprecated, please pass in an Options object
  browser = webdriver.Firefox(firefox_profile=profile,options=options)
Logging in ***@***.*** automatically...
Traceback (most recent call last):
  File "/Users/petermate/Downloads/facebook-friends-map-master/make.py", line 371, in <module>
    signed_in = sign_in()
                ^^^^^^^^^
  File "/Users/petermate/Downloads/facebook-friends-map-master/make.py", line 67, in sign_in
    email_id = browser.find_element_by_id("m_login_email")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'
(facebook-friends-map-master) ***@***.*** facebook-friends-map-master % pipenv shell



Thanks! :)
